### PR TITLE
[ETH/WETH] Show warning if user native funds low

### PR DESCRIPTION
**Pull request by W3stside**
Part of #499

Shows error if user's native balance is lower than the static `0.1` threshold set in constants

### Styling by @biocom in #497 will make this look better

too low input
Screenshot from 2021-04-23 11-20-32

difference would leave too little
Screenshot from 2021-04-23 12-37-58

QA Testing
1. select an account with lessThan 0.1 in native token (ETH/XDAI)
2. select ETH SELL
3. select erc20 BUY
4. input an amount lessThan native balance
5. Error should show with wrapping component

### CODE REVIEW

**Comment by biocom** [comment]
Suggestion for wording: 
> WARNING! After wrapping your ETH, your balance will fall below < 0.1 ETH. As a result you may not have sufficient ETH left to cover future on-chain transaction costs.

This clarifies and communicates two actionable points:
- The recommended threshold balance to keep (we currently hard code 0.1 ETH)
- That the lower balance would be the case *after* wrapping their ETH (wording could suggest now, you don't have enough ETH to do the WRAPPING itself).

**Review by biocom — APPROVED** [review]

**Review by biocom — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
I feel the text and line space is to small. Makes the message hard to read.

For estimating how much fee is needed 

Also, I'm starting to think the MAX behaviour shouldn't use the 0.1 (or whatever limit we define). Because if a user wants to wrap MAX he should get a help. I guess uniswap checks to the estimation so you end up with 0 after the WRAPING. Probably this part shouldn't be touched. 

Then, lastly I think we saw in the demo today that is good to increase the warning theshold. I would show it if you have "low balance" after wrapping. 
"low balance" should we increase it to 0.5 ETH? 

One other user is that xDAI we are using 0.1 ETH wich is too little. So maybe is not bad approach to do the estimation. And leave ether for 10 transactions, or 20 tx. Not sure...

WDYT?


image

**Comment by anxolin** [comment]
@W3stside is in your radar to do the confirmation dialog too?

**Comment by biocom** [comment]
> I feel the text and line space is to small. Makes the message hard to read.
> 
> image
> 
> For estimating how much fee is needed
> 
> Also, I'm starting to think the MAX behaviour shouldn't use the 0.1 (or whatever limit we define). Because if a user wants to wrap MAX he should get a help. I guess uniswap checks to the estimation so you end up with 0 after the WRAPING. Probably this part shouldn't be touched.
> 
> Then, lastly I think we saw in the demo today that is good to increase the warning theshold. I would show it if you have "low balance" after wrapping.
> "low balance" should we increase it to 0.5 ETH?
> 
> One other user is that xDAI we are using 0.1 ETH wich is too little. So maybe is not bad approach to do the estimation. And leave ether for 10 transactions, or 20 tx. Not sure...
> 
> WDYT?

Small text/error styling addressed in https://github.com/gnosis/gp-swap-ui/pull/497

**Comment by W3stside** [comment]
@anxolin will do that in another PR

**Review by anxolin — APPROVED** [review]
@W3stside approving since I understand the comments will be addressed in other PRs

**Pull request merged**
