### PR TITLE
Update uni v3.2.14

### PR DESCRIPTION
**Pull request by alfetopito**
Updating upstream from v3.2.6 to v3.2.14

https://github.com/Uniswap/uniswap-interface/compare/v3.2.6...v3.2.14

Decided to try the update to fix the WalletConnect issue.
Unfortunately, it didn't.
But, already had the effort, let's roll with it.

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
Good call!

They did change sth regarding WC, but only to add a more reliable bridge:
image


I would suggest to change the PR to DRAFT, cause we need to take a closer look to all changes, make sure we understand them and do the changes needed. 

For example, for that change, we would like to use our own bridge instead of theirs.

**Comment by alfetopito** [comment]
> Good call!
> 
> They did change sth regarding WC, but only to add a more reliable bridge:
> image
> 
> I would suggest to change the PR to DRAFT, cause we need to take a closer look to all changes, make sure we understand them and do the changes needed.
> 
> For example, for that change, we would like to use our own bridge instead of theirs.

Alright, moved to DRAFT.

BTW, the only change that was needed to make the app work was on Swap page. I already sync'd it to SwapMod -> https://github.com/gnosis/gp-swap-ui/pull/423/commits/61b5587f9b66f131bb56105a5954a400ad4d5e4f
Everything else seems to have been merged cleanly.

I'll additionally change Uniswap's bridge to our own.
Anything else you think we need to change?

**Review by anxolin — APPROVED** [review]
Yep, all seems good. Thx

**Review by W3stside — APPROVED** [review]
looks/works fine

**Pull request merged**
