### PR TITLE
Reduce changes swap mod

### PR DESCRIPTION
**Pull request by anxolin**
This PR moves quite some logic form the Mod to our index. It does so by creating smaller components that are injected to the SwapMod

This changes are applied on top of #449 

This way the Mod are now easily comparable. 
Also uses the word Fee instead of Fee/GP for coherence with other parts.

----------------
EDIT 1: 

~~It has a small issue. I think I have an additional DIV or something breaking the layout a bit.~~
~~probably an easy fix. Ill look at this later, but @W3stside if you want to go for it, also do.~~

----------------
EDIT 2: Fixed!

### CODE REVIEW

**Comment by alfetopito** [comment]
Me likey. Except the part where it broke :D
But yeah, that's what I've used before and what I suggested to Michel here https://github.com/gnosis/gp-swap-ui/pull/440#discussion_r614213014

**Comment by alfetopito** [comment]
Something is still wrong.
The active token no longer has a background
screenshot_2021-04-16_10-54-00

**Comment by anxolin** [comment]
@alfetopito, I believe is because it has the focus. Click outside and you will get the background again. 
This is already happening in DEV, so no part of this PR

**Comment by anxolin** [comment]
Merging as agreed with David!

**Pull request merged**
