### PR TITLE
[Part of fee] Show correct input amount in pending order toast

### PR DESCRIPTION
**Pull request by W3stside**
Was showing the `adjustedInputAmount` - how shows the proper expected `inputAmount`

Screenshot from 2021-02-25 17-55-12

### CODE REVIEW

**Comment by anxolin** [comment]
3 notes, I write for tomorow, when I plan to review more carefully. 

**Issue with TO amount**
Although the FROM looks good, I'm not 100% sure about the "TO" message you show.

Judging by the numbers, you've used the estimation of the received tokens for the "Waiting for confirmation", but uses the Minimum received tokens for the toast and recent transactions. We should be coherent, and reason why we use one or the other. 

Functionally I think we cannot do as uniswap (that use the estimation), we probably should say "Sell XXX for at leat YYY" (and use always the minimum) or sth like that. When the trade is confirmed, ideally we show the actual amount received in the trade.

**Missing thinkinging process**
I would tell you the same as #158 , it's best if in the description you show the reasoning with the numbers of what you did. This way I can validate the math without going over the PR. Also, I can make sure you test it thoroughly in situations like BUY ORDER, SELL ORDER and you have clear what you expect.

**Icon of sent tx**
One more thing, not related to this PR but nice to review, is the icon used when we send a tx to the operator. It shows success, but it should show that it was delivered but now is waiting time. By it looks, it seems like you traded already when you haven't 
image

cc/ @biocom  maybe u want to suggest a better icon

**Change
I'll continue tomorrow, cause I'm also confused by seeing so many changes. here

**Review by alfetopito — APPROVED** [review]
Nice job!

**Review by alfetopito — CHANGES_REQUESTED** [review]
Forgot to mention: integration tests :grin:

**Comment by W3stside** [comment]
> 3 notes, I write for tomorow, when I plan to review more carefully.
> 
> **Issue with TO amount**
> Although the FROM looks good, I'm not 100% sure about the "TO" message you show.
> 
> Judging by the numbers, you've used the estimation of the received tokens for the "Waiting for confirmation", but uses the Minimum received tokens for the toast and recent transactions. We should be coherent, and reason why we use one or the other.
> 
> Functionally I think we cannot do as uniswap (that use the estimation), we probably should say "Sell XXX for at leat YYY" (and use always the minimum) or sth like that. When the trade is confirmed, ideally we show the actual amount received in the trade.
> 
> **Missing thinkinging process**
> I would tell you the same as #158 , it's best if in the description you show the reasoning with the numbers of what you did. This way I can validate the math without going over the PR. Also, I can make sure you test it thoroughly in situations like BUY ORDER, SELL ORDER and you have clear what you expect.
> 
> **Icon of sent tx**
> One more thing, not related to this PR but nice to review, is the icon used when we send a tx to the operator. It shows success, but it should show that it was delivered but now is waiting time. By it looks, it seems like you traded already when you haven't
> image
> 
> cc/ @biocom maybe u want to suggest a better icon
> 
> **Change
> I'll continue tomorrow, cause I'm also confused by seeing so many changes. here

wrong base branch, fixed. this PR is just for using the correct FROM number, but i will apply this to the other PR

**Review by alfetopito — APPROVED** [review]
:feelsgood:

**Review by anxolin — APPROVED** [review]
Ok, cool. I approve this one since the FROM is good here. And we discuss all the other things in the #183

**Pull request merged**
