### PR TITLE
Unsupported Tokens - update FAQ links + modal content

### PR DESCRIPTION
**Pull request by W3stside**
Properly links to FAQ section from currency list and swap modal when unuspported token detected.

in swap modal for unsupported tokens it shows the tokens and links to etherscan

### CODE REVIEW

**Review by biocom — APPROVED** [review]

**Comment by avsavsavs** [comment]
looking good!! The only thing is that when you click FAQ link, the question is not there yet

**Comment by W3stside** [comment]
> looking good!! The only thing is that when you click FAQ link, the question is not there yet

target blank opens a new tab and the hashlink doesn'tknow how to hit the header from a new tab. for now it's acceptable but we can maybe look into hacking this a bit to wait and scroll if no other solution

**Review by alfetopito — APPROVED** [review]
The FAQ contents will be updated in another PR, right?

**Review by anxolin — APPROVED** [review]
Tiny detail, should we include the question that explain why the tokens are not supported already in the modal? (while this is not fixed https://github.com/gnosis/gp-swap-ui/issues/650)

I'm referring to add it here:
image

Maybe also, add more space for the phrase "For more information...." so it is in it's own paragraph

**Pull request merged**
