### PR TITLE
Improve logo app status/header component.

### PR DESCRIPTION
**Pull request by biocom**
- Header bottom border now takes in a theme variable (no bottom border for Cow Swap)
- Restoring ALPHA title (lost in Anxo' PR). Essentially it wasn't overriding the Mod.
- Improve mobile responsive logo size (compacter).

### CODE REVIEW

**Review by W3stside — CHANGES_REQUESTED** [review]
nice work but the way you modded is a bit incorrect:

Inside `custom/components/Header/HeaderMod.tsx` you have `UniIcon` already there. Please comment out the pieces you don't need/adding your own, and not changing the name in the `index` file. Let me know if that wasn't clear and i can help

**Review by alfetopito — APPROVED** [review]

**Comment by W3stside** [comment]
@biocom

**Comment by biocom** [comment]
@W3stside Thanks for then nudge. Able to check if it's correct now? I commented out UniIcon in HeaderMod. And now have an identical named styled component in the `index` file.

**Comment by anxolin** [comment]
> @W3stside Thanks for then nudge. Able to check if it's correct now? I commented out UniIcon in HeaderMod. And now have an identical named styled component in the index file.

@biocom remember to signal you want another review by using 
image

**Review by anxolin — APPROVED** [review]

**Pull request merged**
