### PR TITLE
Wallet connect connector

### PR DESCRIPTION
**Pull request by anxolin**
This PR adds support for Wallet Connect in all the supported networks (mainnet, xdai, rinkeby)

This PR depends on `web3-react` merging this PR https://github.com/NoahZinsmeister/web3-react/pull/185. In the meantime, it uses https://www.npmjs.com/package/@anxolin/walletconnect-connector which has the code of that PR in `web3-react`.

## Test
Try to connect to Rinkeby using Wallet Connect. See if you load the balances

Note: I didn't test if you can sign messages yet. It may or may not work. In any case, I wouldn't consider that part of this PR. 

image

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
It worked!

Order placed using MM mobile: https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x1d7332c2e2155ac6123b6f2922fa0e780691dedeca6717064ee1cab199f2adea5b0abe214ab7875562adee331deff0fe1912fe42607883d1

Took me awhile, didn't work at first, lot's of back and forth, but finally worked :)

**Comment by alfetopito** [comment]
After a lot of struggle, managed to connect Trust wallet. But it is very unstable.
Constant showing error messages, and lots of these logs on the browser:
screenshot_2021-04-15_11-29-23

I was able to wrap ETH and approve WETH without many issues.
Just lack of feedback on the UI after the button is clicked because it takes ages for the pop-up to show in the wallet.

And these screenshots are on the Trust wallet side.

This nice thing is the signature request. Very user friendly
Screenshot_20210415-111544

This showed up several times after I signed the one above
Screenshot_20210415-112536

The order is forever pending, and I don't think it was ever posted as the UI didn't receive the data from the bridge
screenshot_2021-04-15_11-32-47

So, big NOT WORKING for Trust wallet.
Then again, we already decided to drop it.

**Comment by anxolin** [comment]
@alfetopito, this PR was meant only to add multi-network support for Wallet Connect. 

WC is disabled, so I would just consolidate this and fix later all pending issues.

**Comment by alfetopito** [comment]
> @alfetopito, this PR was meant only to add multi-network support for Wallet Connect.
> 
> WC is disabled, so I would just consolidate this and fix later all pending issues.

I know. Just testing to see what we got so far :)

**Comment by anxolin** [comment]
Closing and merging, @W3stside u can still review post-merge

The point is that if this breaks anything, we would see it sooner, since we close version in 2 days. It shouldn't affect, since WC is disabled anyways now in develop

**Pull request merged**
