### PR TITLE
[0.13] Price Race Conditions

### LINKED ISSUE #709: Test for race conditions
**Describe the bug**
Probably the issues we see sometimes with the price on the new version has to do with the debounce issue.

Probably all issues are gone after solving: #691 
However, I'm leaving this issue to make sure we test thoroughly for rance conditions. I expressed my concern about race conditions in https://github.com/gnosis/gp-swap-ui/pull/668/files#r640554913 I think we need to tackle this issue better.

**How to Reproduce**

https://user-images.githubusercontent.com/2352112/119998445-fe91c180-bfd0-11eb-8f6c-987044bba4ed.mov

### PR DESCRIPTION
**Pull request by W3stside**
Partly closes #709 (race condition from consecutive price fetches)

Uses the anxo recommended https://github.com/slorber/awesome-only-resolves-last-promise lib to wrap `getQuote` and only return the last call in a a subsequent series of calls.

Tested in console by logging fn and calling in succession:
image

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
I love the simplicity of the implementation, although, I'm wondering what happen with the 

`const [price, fee] = await getQuote(params)` for the promises that don't resolve...
Would this be creating a memory leak by leaving promises that never resolve?

**Review by alfetopito — APPROVED** [review]
Looks ok to me

**Comment by W3stside** [comment]
@anxolin superseded?

**Comment by W3stside** [comment]
superseded by #722

**Pull request closed without merging**
