### PR TITLE
Show fee warning

### LINKED ISSUE #211: [Fee] When input amount is lower than fee amount - show relevant message
**GP/Gas fees is only visible when trade is validated**

Scenario: user selects input amount that is lower than the minimalFee threshold, the trade will not be validated. However user cannot see the fee amount at this point so it is unclear with the `Insufficient Liquidity` what is going on

Solution: always show `sellToken` fee amount and a better message for clarity

### PR DESCRIPTION
**Pull request by W3stside**
Closes #211 

Shows to the user in the Submit button wording that their input amt < fee
also shows the fee amt to user

here:
Screenshot from 2021-03-18 15-02-06

### CODE REVIEW

**Comment by fleupold** [comment]
Cool! It might be nice to know somehow what the minimum input amount is (but I also see the benefit of the concise message).

**Comment by W3stside** [comment]
> Cool! It might be nice to know somehow what the minimum input amount is (but I also see the benefit of the concise message).

Yeah this part is always very subjective and hard. What about a MIN button next to MAX?

**Comment by fleupold** [comment]
> What about a MIN button next to MAX?

I'm not sure people actually want to trade the minimum amount (as this would give them 0 proceeds and only pay for fee) so I don't think we need a call to action. It might just be useful to show the fee amount somehow even if the min trade amount is not reached.

**Review by anxolin — COMMENTED** [review]
The units are incorrect for buy orders.
image


nit: for the message "Fees exceed input amount". I would use "from amount" since that's what the label has. 

Also, I think our message styles should be coherent. For example this message shows the error message like this:
image

But insufficient balance shows it like this:
image

Why not showing exactly the same layout. Maybe we can hide the price impact, but the rest should be fine.

**Comment by W3stside** [comment]
@Mergifyio update

**Comment by W3stside** [comment]
> Why not showing exactly the same layout. Maybe we can hide the price impact, but the rest should be fine.

Uni returns `null` when the input amount is <= `0` - following this pattern, an order with an input amount lower than the fee would return `null`, thus having no available data for that trade breakdown dropdown

IMO it's best to keep the same UX. I can change the warning to be more inline with the Uni style and maybe add some colouring to make it stand out.

_if_ we really want to show the breakdown when the fee > input, then it's possible but imo it isn't useful seeing as: `Minimum Received` would be `0` or `-` (can't make anything when the fee > input) and the `price impact` would be gone, leaving only the gas, which we are already showing

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
