### PR TITLE
[Fee] ConfirmationModal Mod: show updated fee information

### LINKED ISSUE #173: Trade confirmation modal: Improve the message
image

Change this text: `Input is estimated. You will sell at most 0.669872 ETH or the transaction will revert.`

Our tx don't REVERT. They EXPIRE. 

`Input is estimated. You will sell at most 0.669872 ETH or the transaction will expire in XXXX min`

Same for these other tooltips: 

image
image

We shouldn't use the REVERT word.

### PR DESCRIPTION
**Pull request by W3stside**
Part of #161 

Closes #173 

Updates the `ConfirmationModal` to show the correct info relevant to the changes agreed in #161 

Mods: `ConfirmSwapModal` and `SwapModalFooter`

Screenshot from 2021-03-02 15-04-17

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
I would try to find a message that sells our protocol idea that you don't pay if the prices moves or if the date expires (this is an issue in Uniswap).

**Proposal:**
1. confirmation modal: Input estimated. You will sell at most 0.67123 ETH or the transaction won't execute. No fees will be charged if this happens
2. helper for expire date: Your transaction will expire if it is pending for more than this long. No fees will be charged if this happens
3. helper for slippage:  Your transaction won't be executed if the price changes unfavorably by more than this percentage. No fees will be charged if this happens

context:
https://gnosisinc.slack.com/archives/CPZA1AGKY/p1614792902032400?thread_ts=1614792372.029500&cid=CPZA1AGKY

**Comment by W3stside** [comment]
@anxolin ok all good points but these PRs are waterfalling a bit out of control. Can you approve / reject this based on the code and not the content of the message? I would like to consolidate these

**Comment by W3stside** [comment]
merging for clean up, will create new PRs to address any outstanding comments

**Comment by anxolin** [comment]
All good, can you pls follow up https://gnosisinc.slack.com/archives/CPZA1AGKY/p1614792372029500 and make sure we take a good decission?

**Pull request merged**
