### PR TITLE
Enable Wallet Connect (EOA)

### PR DESCRIPTION
**Pull request by anxolin**
## WIP: Enable WC 🚽

Using this Google Sheets to track the wallets and where is working!
https://docs.google.com/spreadsheets/d/177RoN3x0gHDwKAgu-TXUYEuz-z-dPu3RybZvOumRrAA/edit#gid=0

### CODE REVIEW

**Comment by W3stside** [comment]
yoo this is sick! works great with MM mobile and walletconnect, change networks, accounts, all reflected and amounts updated

**Review by W3stside — APPROVED** [review]
Android, MM mobile, worked great.

**Comment by anxolin** [comment]
@MareenG I'm doing some tests already. If you want to jump into it, great.
We can coordinate in the google sheets

**Comment by alfetopito** [comment]
Superseded by https://github.com/gnosis/gp-swap-ui/pull/597

**Pull request closed without merging**
