### PR TITLE
Pr comments/311/web links

### PR DESCRIPTION
**Pull request by W3stside**
Merges into #311 

Screenshot from 2021-04-01 15-52-30

Adds Etherscan and Github links

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
I'm not personally super found of the logos.
But, I'll leave this up to the professionals (@biocom)

**Comment by biocom** [comment]
> I'm not personally super found of the logos.
> But, I'll leave this up to the professionals (@biocom)

Fine for now, can improve in a separate PR.

**Comment by W3stside** [comment]
can i get approvals here if it's ok @biocom @alfetopito

**Review by biocom — APPROVED** [review]

**Comment by W3stside** [comment]
merging with 1 approval as not really app breaking

**Pull request merged**
