### PR TITLE
Add Github actions CI workflow

### PR DESCRIPTION
**Pull request by anxolin**
Deploys the web: PRaul + DEV + STAGING. Also do test (unit+integration)

It requires to setup the secrets in https://github.com/gnosis/gp-swap-ui/settings/secrets/actions

image

## Not included
Integration tests are broken. They need to be fixed in another PR. I'm opening an issue

### CODE REVIEW

**Review by giacomolicari — APPROVED** [review]
Looks great!

**Review by alfetopito — CHANGES_REQUESTED** [review]
Missing some config on AWS? Wrong bucket name?
screenshot_2021-01-21_10-22-44

**Comment by anxolin** [comment]
> Missing some config on AWS? Wrong bucket name?
Yep, already notified in devops channel for getting some help.

cc/ @giacomolicari

**Comment by anxolin** [comment]
@alfetopito Giaco, fixed it. So now it's working :) 
I'll merge it. Let me know if there's any post-merge comments to address

**Pull request merged**
