### PR TITLE
Update contract version package

### PR DESCRIPTION
**Pull request by anxolin**
Merge alpha-11 version

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr100--gpswapui.review.gnosisdev.com)**: Testing web app

**Comment by anxolin** [comment]
Might be related to  #99

**Review by W3stside — APPROVED** [review]
why is this a draft?

**Comment by anxolin** [comment]
Closed, it was upgrade already in another PR

**Pull request closed without merging**
