### PR TITLE
[135b] Replaces 155 - possible fixes fee calculation in Trade and trade.ts "postOrder" method

### LINKED ISSUE #135: Do not include fee in the signed "sell amount"
"From" deducts fee in estimate but not in signed order

Assume the following order and a fee endpoint returinng a hardcoded 1 wxDAI:

image

The amount in To (estimated) is computed as if we were selling 1 wxDAI (From - fee). However the order that gets eventually signed and sent to the backend is for selling 2 wxDAI **AND** 1 wxDAI fee on top.

Given the current UX (which is under discussion in ) it should only be signed for a sell amount of 1 wxDAI. Otherwise the smart contract will take up 3 wxDAI from the User's balance and the user is signing a limit price that is way too pessimistic.

Cf this settlement where the fee was 0.1 wxDAI (and I typed in 2 in the From field): https://blockscout.com/poa/xdai/tx/0xd2a58cec3c5ea3a9a6780699a260d42021e49290f3a96e2b260c6874b138e34e/token-transfers

### PR DESCRIPTION
**Pull request by W3stside**
Possible supersedes #155 

Closes #135 

1. removes fee calculation inside `trade.ts` as discussed @anxolin and passes the amounts from the Trade calculation before
2. adjusts types/props on extension trade object similar to #155

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
I think for this PRs is useful if you provide a quick example in the description that allows to do a check on the numbers.

I'll do it myself now, but pls remember it next iteration, since it really helps with the review:

## Test CASE
* Network: Ribkeby
* from: 100000000000000 USDT
* to: 0.828583 USDC
* price 119448000000000 USDT per USDC

## API: The fee is
* expirationDate: "2021-02-19T10:39:34.323832405Z" 
* feeRatio: 0 
* minimalFee: "1027049734971308032 "

## Swap callback
```
[useSwapCallback] >> Trading USDT → WETH → USDC. 
            1. Original Input = 100000000000000
            2. Fee = 1027049734971.308032
            3. Input Adjusted for Fee = 98972950265028.691968
            4. Output = 0.82446
            5. Price = 0.0000 
```
## Signed data

```
sellToken:
0xd9ba894e0097f8cc2bbc9d24d308b98e36dc6d02
buyToken:
0x4dbcdf9b62e891a7cec5a2568c3f4faf9e8abe2b
sellAmount:
0x55d868de287704800
buyAmount:
0xc948c
validTo:
0x602f9a38
appData:
0x0
feeAmount:
0xe40d04adb9fb800
kind:
sell
partiallyFillable:
false
```

## Expected 
Expected sell amount = 100000000000000-1027049734971308032*1e-6 = `98972950265028.691968`

Received sell amount (in the hook) = `98972950265028.691968` ✅

Received sell amount (to sign) = `0x55d868de287704800` = `98972950265028691968` ✅

Expected Fee = `1027049734971.308032` --> `1027049734971308032`
Received fee amount (to sign) = `0xe40d04adb9fb800` = `1027049734971308032` ✅

Expected to amount (without slippage): `824460` --->    `0.824460` 
Expected to amount (without slippage): `820337.7 ` ---> `0.8203377` 

Received Amount ` 0.82446` ❌ 

## Notification
* Expected Message: `Swap 100000000000000 for 0.824460 USDC`

* Received: 
    * From:  ❌
    * To: ❌
image

**Comment by anxolin** [comment]
When you run your tests, please make sure you also test changing the slippage to something other than 0.5% plss

**Comment by W3stside** [comment]
@anxolin @alfetopito this PR can probably be closed, its behind in commits, not merged, and a less clean version of my latest, which addresses showing the fee properly in the UI (it has all these commits in it as it's waterfalled) >> #183 

can i close this and we review there?

**Comment by anxolin** [comment]
Ok, if u superseded your PR, we can kill this one, sure is yours :)

**Comment by W3stside** [comment]
closing in favour of consolidated #183

**Pull request closed without merging**
