### PR TITLE
Fix integ tests

### PR DESCRIPTION
**Pull request by alfetopito**
Attempt at fixing failing cypress integration tests.

From what I could gather, something is causing browser cross origin issues
screenshot_2021-03-03_14-00-17

Tried to run last passing CI build locally (https://github.com/gnosis/gp-swap-ui/pull/185 for commit afaa401), but got the error above.
The only thing I could guess that's causing that would be an updated browser version that's more security strict.
Otherwise, code is the same (package versions, lock file, etc), so should also pass locally...

Anyway, turned it off with https://docs.cypress.io/guides/guides/web-security.html#Disabling-Web-Security

Still some hit and miss tests locally. Pushing first to check whether CI results are different from local

### CODE REVIEW

**Comment by alfetopito** [comment]
I have a hunch of what might be causing a test to fail now

The test:
screenshot_2021-03-03_16-03-08

It fails because there's no liquidity between the pair.

But when manually accessing the pair it does have it.

--

All infura queries on the test are failing with 403, even with different infura keys:
screenshot_2021-03-03_15-54-40
I suspect whatever was "fixed" by turning the web security off is causing the same issue.

**Comment by alfetopito** [comment]
Maybe it's an issue with the infura node? https://community.infura.io/t/getting-403-client-error-forbidden-for-url-when-calling-the-same-function-twice/1259

**Review by W3stside — APPROVED** [review]

**Comment by alfetopito** [comment]
Alright, more data about the issues now (no solutions yet)

1. Running cypress against local host:
- Due to some unknown magic, the app has a connected wallet set to rinkeby
- Tests pass, because it expects Rinekeby tokens to be visible
1. Running against a local build (similar to CI)
- As I would expect, there's no connected wallet, so everything it's running against Mainnet
- Tests that expect rinkeby tokens of course fail
- Even if I set the token to mainnet, it's still fails because it expects a connected wallet.

Now trying to figure out why/how local has a wallet connected

--- 

FYI, added a way to debug CI.
When Cypress step fails, a tmate session opens (check the workflow)
screenshot_2021-03-04_13-32-01

That might not be very useful in itself, but we can use [magic-wormhole](https://magic-wormhole.readthedocs.io/en/latest/welcome.html) to download the test assets.
For now I just manually installed it on the instance, served the screenshots folder and received it on my machine:

```bash

# remote machine
$ sudo apt-get install magic-wormhole
# ... install stuff ...
$ wormhole send cypress-custom/screenshots

# local machine
# install the magic-wormhole first, of course
$ wormhole receive
```

**Comment by alfetopito** [comment]
Found where the magic happens https://github.com/gnosis/gp-swap-ui/blob/develop/cypress/support/commands.js#L71-L79
Although still don't understand how it does the magic.
It seems to be loaded on both occasions, but when using the `prod` build it's not loaded...?

**Comment by alfetopito** [comment]
Don't know why it didn't work with the prod build.
What matters is that it works with the dev build :)

**Comment by W3stside** [comment]
@alfetopito is this good to go? not really sure what `tmate` is, do we want it?

**Comment by W3stside** [comment]
tests are passing locally for me, merging

**Comment by alfetopito** [comment]
> @alfetopito is this good to go? not really sure what `tmate` is, do we want it?

https://tmate.io/

In summary, remote terminal, that we can use to ssh into the CI instance and debug stuff

**Pull request merged**
