### PR TITLE
inputAmountWithFee > inputAmount

### PR DESCRIPTION
**Pull request by W3stside**
Merges into #559 

Use `inputAmount` instead of `inputAmountWithFee` as we want it to match what the user inputs

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
Thanks!

But shouldn't be depending if it's ell order or buy order? 
https://github.com/gnosis/gp-swap-ui/pull/559#issuecomment-829120144


- sellOrders, what he types is what we need to wrap
- buyOrder is what is calculated in the FROM, but + fees, so we wrap the maximum amount that would take the trade considering fee and slippage

**Review by anxolin — DISMISSED** [review]
I'm afraid for buy orders is still not correct

image

Slippage might require more tokens from the user. It's not nice to ask to wrap also for the slippage, but it's needed.

Probably this calls for improvement on how to present this case (better messages), but for this PR at least we should use the right value. 

@biocom any input how to best handle wrapping for buy orders?

**Comment by anxolin** [comment]
we are not done yet, sorry to say 😅

We have this:
image


But more importantly:
image

**Comment by W3stside** [comment]
@anxolin @alfetopito merging to consolidate, we can discuss in #559

**Pull request merged**
