### PR TITLE
Release/0.12

### PR DESCRIPTION
**Pull request by anxolin**
## Do not Squash 🥒, just normal merge

```
# To get commits used in the description (useful for next releases) 
git log master..HEAD --oneline --decorate=0
```

# 💪Work In Progress
🚨This version is not ready to be merged!!🚨 
Pending to incorporate some open PRs:
* ~Unsupported tokens #623, #628~ 
* ~Display price loaded from API: #611, #625~
* Fix issues:
  - Flipping issue: invariants: If you start to swich tokens several times. You break it #623
  - When I first load the price, I see a price that is completely off. Then it corrects itself automatically. Observed in #623
  - Amounts issue when you flip: We need to review because it was modifying the amounts wswitchinghing tokens
  - Max amount issue: insufficient liqudity. Observed in #623
  - ~Button disappearing --> the actual SWAP button next to the APPROVE button~ #631 
  - Max amount issue -> Says insufficient balance when hitting the 'MAX' button. If you provide too low of an amount it will show - "INSUFFICIENT LIQUIDITY". The only way it works is by inputting an amount somewhere in the middle (e.g. 50% of your SELL token balance) -> Happens on https://pr625--gpswapui.review.gnosisdev.com/#/swap
  - UI broken / sender address -> Fixed in #622 

# Release notes (QA instructions)
TODO

- [ ] RC.0 Testing

@MareenG this just means we are freezing this version. On monday we will try to fix some bugs and create a Release Candidate in Staging so you can test. For now, it has too many bugs.

# Changelog
TODO

### CODE REVIEW

**Comment by W3stside** [comment]
@MareenG @anxolin @alfetopito RC.0 is first go into master for testing

**Comment by MareenG** [comment]
Was it intended that the confirm swap modal for **buy orders** now shows the price without the fees? 
Before: 
Bildschirmfoto 2021-05-18 um 09 42 48
Bildschirmfoto 2021-05-18 um 09 42 54

Now
Bildschirmfoto 2021-05-18 um 09 42 33
Bildschirmfoto 2021-05-18 um 09 42 39

**Comment by W3stside** [comment]
> Was it intended that the confirm swap modal for **buy orders** now shows the price without the fees?
> Before:
> Bildschirmfoto 2021-05-18 um 09 42 48
> Bildschirmfoto 2021-05-18 um 09 42 54
> 
> Now
> Bildschirmfoto 2021-05-18 um 09 42 33
> Bildschirmfoto 2021-05-18 um 09 42 39

Nope! Sure wasn't. Will fix this good catch!

**Comment by MareenG** [comment]
Concerning the Pending list above, the things that are crossed are already merged and should be ready to be tested, right?

**Comment by W3stside** [comment]
> Concerning the Pending list above, the things that are crossed are already merged and should be ready to be tested, right?

Yep, i am opening the next RC, rc.1 soon to provide more details, hang tight @MareenG

**Comment by MareenG** [comment]
There is a minor error, I didn't want to open an issue for.
Bildschirmfoto 2021-05-18 um 09 13 52
I think the space needs to be removed

**Pull request merged**
