### PR TITLE
Styling of the feedback button.

### PR DESCRIPTION
**Pull request by biocom**
- Adds styles for the feedback button
- Fixed z-index interference with any open modals (e.g. token selector list)

Mobile:
Screen Shot 2021-04-26 at 15 10 24

Desktop:
Screen Shot 2021-04-26 at 15 10 09

Hover/Tap:

https://user-images.githubusercontent.com/31534717/116089493-39879900-a6a3-11eb-871d-e374fefface9.mp4

No more interference with open modals or overlaying token selector menu's:

https://user-images.githubusercontent.com/31534717/116089511-3db3b680-a6a3-11eb-84c1-b1056260c2ae.mp4

### CODE REVIEW

**Review by anxolin — APPROVED** [review]

**Comment by anxolin** [comment]
It's really great. The only nitpick, is a weird effect in mobile. One interference with the footer for just 1second, when we show the label

IMG_32B87C080E66-1

**Comment by biocom** [comment]
@anxolin Did an update to remove the tooltip on mobile.

Currently the plugin, when the feedback modal is opened, adds a class to the `body` element which contains there properties:
- position: fixed
- overflow: hidden

Given our initial page has the scrollbar, this causes a 'jump' on the layout. Let me know if you still have this issue with this update.

**Comment by anxolin** [comment]
I think now doesn't show the message, but the weird effect is still happening:

IMG_CC138AC531FE-1

**Comment by biocom** [comment]
@anxolin Can you clarify:
- What steps do I take to reproduce?
- What browser + version?

I tried to replicate on Android with the latest Chrome/Firefox and both didn't product this reported behavior.

**Comment by anxolin** [comment]
oh noo :) then it must be a IOS only thing

I just click the button, and I get that weird effect between the click and the display of the modal dialog.

if you don't have IOS to reproduce, maybe we can debug tomorrow, is not that important. You can open an issue, and we merge this PR is a nitpick anyways

**Pull request merged**
