### PR TITLE
703/mev wallet

### LINKED ISSUE #703: [Wallets] MEV Mobile doesn't work
**Describe the bug**
MEV Mobile Android wallet dApp browser can't sign orders.
It fails with "RPC request failed"

**How to Reproduce**
1. With an Android phone, install the app https://www.mewwallet.com/
2. Using the internal dApp browser, visit https://cowswap.staging.gnosisdev.com/#/swap
3. Insert all the required fields (both token, sell/buy amount)
4. Click on `Swap`

**Expected behavior**
A signature prompt is displayed

**Screenshots**
N/A

**Additional context**
Probably v4 is not supported, need to check which version is.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #703 

The wallet fails when trying `eth_signTypedData_v4` with the very clear error message:

```
{"name":"Error","message":"RPC request failed","stack":"Error: RPC request failed\n at TrustWeb3Provider.value (http://archameba.lan:3000/:685:7364)\n at :1:17"}
```

Are they using Trust behind the scenes?
Whatever

The fix is to watch for that error message, and try other signing methods.
It worked with `v3` :+1: 

The caveat: even though it supports v3, this is what the wallet shows when the signature is requested:
Screenshot_20210527-140219

:shrug: 

# Testing

1. Using MEV wallet for Android (dApp browser not available on iOS), load this PR's app url
2. Place order
- [ ] The signature (although empty) should prompt
- [ ] The order should be placed successfully

### CODE REVIEW

**Comment by anxolin** [comment]
@alfetopito how can you connect in the first place? 
I really don't know how. In my cases it says it uses MEV connect, not Wallet Connect:

image


What am i missing?

**Comment by alfetopito** [comment]
> @alfetopito how can you connect in the first place?
> I really don't know how. In my cases it says it uses MEV connect, not Wallet Connect:
> 
> What am i missing?

You are missing Android :)
screenshot_2021-05-28_07-44-28

**Review by anxolin — COMMENTED** [review]
I can't approve this, I have no way of testing. I'll leave it up to David and Michel

**Review by W3stside — APPROVED** [review]
everything worked for me!

**Review by biocom — APPROVED** [review]

**Comment by biocom** [comment]
Works well A+++, can recommend.

**Review by Lucid36 — COMMENTED** [review]
Duplicate of #

**Pull request merged**
