### PR TITLE
Release/0.6.0

### PR DESCRIPTION
**Pull request by anxolin**
## Do not Squash 🥒, just normal merge

```
# To get commits used in the description (useful for next releases) 
git log master..HEAD --oneline --decorate=0
```

# v0.6.0

## Highlights
- Fixed issue with negative slippage
- Better token selection for xDAI and Rinkeby
- Fixed some issues with the expiration date: It was failing if the user creates 2 orders with the same data very fast
- Update from version v3.0.8 of Uniseap to v3.2.3. Lot's of UI improvements. More details https://github.com/gnosis/gp-swap-ui/pull/160 
- Add links to the explorer
- Remove claim modal from Uni token
- Add analytics
- Don't allow to trade ETH, show a message and help the user to WRAP/UNWRAP
- Show the fee
- Lot's of fixes, specially related to the fee the signed amounts, and the messages shown in the toasts.

## Details
c0995a0 Fix order placement (#240)
fc3de26 Fixed issues with order validTo: (#232)
4cbd9a6 [107] Tokens by network (#177)
13e7db5 186/no popup for old notifications (#222)
2adab05 163/Fix wrong wallet name (#225)
17a64bb Point fulfillment pop-ups to explorer instead of etherscan (#224)
9bf75c5 [161] Show GP/Gas Fee properly (#183)
369acb6 rollback to working alpha.11 (#220)
394f665 Improve ETH UX (#200)
274db14 Fix integ tests (#198)
5bd8e6a Test to add analytics (#190)
0d5235f Use our own infura key (#193)
a1ac8e2 fix DAI logo in token list (#191)
3efe961 Remove claim modal (#195)
afaa401 Add links explorer (#185)
a62ded4 Update uni v3.0.8 to v3.2.3 (#160)
79e9653 Fully automate dev setup with Gitpod (#180)
356d281 Rinkeby token list (from dx-react) (#170)
6913abf Hack negative slippage (#166)

### CODE REVIEW

**Comment by fleupold** [comment]
Note, that the backend is not supporting the smart contract version in this PR and therefore this cannot yet work e2e.

**Comment by W3stside** [comment]
@anxolin we're holding off on contract to alpha 14 right? if so should be removed from `highlihgts`

**Review by W3stside — APPROVED** [review]
Good version!

**Comment by anxolin** [comment]
Closing this version, @MareenG I know tests are not over, it just means we freeze and give a name to it.

**Pull request merged**
